// web/src/NodeWithTableView.svelte
<script lang="ts">
  import { type NodeProps } from '@xyflow/svelte';
  import LynxKiteNode from './LynxKiteNode.svelte';
  import Table from './Table.svelte';
  type $$Props = NodeProps;
  export let data: $$Props['data'];
  const open = {};
  $: single = data.display?.dataframes && Object.keys(data.display.dataframes).length === 1;
</script>

<LynxKiteNode {...$$props}>
  {#if data.display}
    {#each Object.entries(data.display.dataframes || {}) as [name, df]}
      {#if !single}<div class="df-head" on:click={() => open[name] = !open[name]}>{name}</div>{/if}
      {#if single || open[name]}
        {#if df.data.length > 1}
          <Table columns={df.columns} data={df.data} />
        {:else}
          <dl>
          {#each df.columns as c, i}
            <dt>{c}</dt>
            <dd>{df.data[0][i]}</dd>
          {/each}
          </dl>
        {/if}
      {/if}
    {/each}
    {#each Object.entries(data.display.others || {}) as [name, o]}
      <div class="df-head" on:click={() => open[name] = !open[name]}>{name}</div>
      {#if open[name]}
      <pre>{o}</pre>
      {/if}
    {/each}
  {/if}
</LynxKiteNode>
<style>
  .df-head {
    font-weight: bold;
    padding: 8px;
    background: #f0f0f0;
    cursor: pointer;
  }
  table {
    table-layout: fixed;
  }
  dl {
    margin: 10px;
  }
</style>

// web/src/workspace/nodes/NodeWithTableView.tsx
import { useState } from 'react';
import Markdown from 'react-markdown'
import LynxKiteNode from './LynxKiteNode';
import Table from './Table';
import React from 'react';

function toMD(v: any): string {
  if (typeof v === 'string') {
    return v;
  }
  if (Array.isArray(v)) {
    return v.map(toMD).join('\n\n');
  }
  return JSON.stringify(v);
}

export default function NodeWithTableView(props: any) {
  const [open, setOpen] = useState({} as { [name: string]: boolean });
  const display = props.data.display?.value;
  const single = display?.dataframes && Object.keys(display?.dataframes).length === 1;
  return (
    <LynxKiteNode {...props}>
      {display && [
        Object.entries(display.dataframes || {}).map(([name, df]: [string, any]) => <React.Fragment key={name}>
          {!single && <div key={name} className="df-head" onClick={() => setOpen({ ...open, [name]: !open[name] })}>{name}</div>}
          {(single || open[name]) &&
            (df.data.length > 1 ?
              <Table key={name} columns={df.columns} data={df.data} />
              :
              <dl key={name}>
                {df.columns.map((c: string, i: number) =>
                  <React.Fragment key={name + '-' + c}>
                    <dt>{c}</dt>
                    <dd><Markdown>{toMD(df.data[0][i])}</Markdown></dd>
                  </React.Fragment>)
                }
              </dl>)}
        </React.Fragment>),
        Object.entries(display.others || {}).map(([name, o]) => <>
          <div className="df-head" onClick={() => setOpen({ ...open, [name]: !open[name] })}>{name}</div>
          {open[name] && <pre>{(o as any).toString()}</pre>}
        </>
        )]}
    </LynxKiteNode >
  );
}
