// web/src/Table.svelte
<script lang="ts">
  export let data, columns;
</script>

<table>
  <thead>
    <tr>
      {#each columns as column}
        <th>{column}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each data as row}
      <tr>
        {#each columns as column}
          <td>{row[column]}</td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

// lynxkite-app/web/src/workspace/nodes/Table.tsx
export default function Table(props: any) {
  return (
    <table>
      <thead>
        <tr>
          {props.columns.map((column: string) => (
            <th key={column}>{column}</th>
          ))}
        </tr>
      </thead>
      <tbody>
        {props.data.map((row: { [column: string]: any }, i: number) => (
          <tr key={`row-${i}`}>
            {props.columns.map((_column: string, j: number) => (
              <td key={`cell ${i}, ${j}`}>{JSON.stringify(row[j])}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
