// web/app/workspace/EnvironmentSelector.tsx
export default function EnvironmentSelector(props: { options: string[], value: string, onChange: (val: string) => void }) {
  return (
    <select className="form-select form-select-sm"
      value={props.value}
      onChange={(evt) => props.onChange(evt.currentTarget.value)}
    >
      {props.options.map(option =>
        <option key={option} value={option}>{option}</option>
      )}
    </select>
  );
}

// web/src/EnvironmentSelector.svelte
<script lang="ts">
  export let options;
  export let value;
  export let onChange;
</script>

<select class="form-select form-select-sm"
  value={value}
  on:change={(evt) => onChange(evt.currentTarget.value)}
  >
  {#each options as option}
    <option value={option}>{option}</option>
  {/each}
</select>
