// lynxkite-app/web/src/workspace/nodes/NodeWithImage.tsx
import LynxKiteNode from "./LynxKiteNode";
import { NodeWithParams } from "./NodeWithParams";

const NodeWithImage = (props: any) => {
  return (
    <NodeWithParams {...props}>
      {props.data.display && <img src={props.data.display} alt="Node Display" />}
    </NodeWithParams>
  );
};

export default LynxKiteNode(NodeWithImage);

// web/src/NodeWithImage.svelte
<script lang="ts">
  import { type NodeProps } from '@xyflow/svelte';
  import NodeWithParams from './NodeWithParams.svelte';
  type $$Props = NodeProps;
  export let data: $$Props['data'];
</script>

<NodeWithParams {...$$props}>
  {#if data.display}
    <img src={data.display}/>
  {/if}
</NodeWithParams>
<style>
</style>
