// web/app/workspace/nodes/NodeWithParams.tsx
import { useContext } from 'react';
import { LynxKiteState } from '../LynxKiteState';
import LynxKiteNode from './LynxKiteNode';
import { useNodesState } from '@xyflow/react';
import NodeParameter from './NodeParameter';

function NodeWithParams(props) {
  const metaParams = props.data.meta?.params;
  const state = useContext(LynxKiteState);
  function setParam(name, newValue) {
    const i = state.workspace.nodes.findIndex((n) => n.id === props.id);
    state.workspace.nodes[i].data.params[name] = newValue;
  }
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const params = nodes && props.data?.params ? Object.entries(props.data.params) : [];

  return (
    <LynxKiteNode {...props}>
      {params.map(([name, value]) =>
        <NodeParameter
          name={name}
          key={name}
          value={value}
          meta={metaParams?.[name]}
          onChange={(value) => setParam(name, value)}
        />
      )}
    </LynxKiteNode >
  );
}

export default NodeWithParams;

// web/src/NodeWithParams.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import { type NodeProps, useSvelteFlow, useUpdateNodeInternals } from '@xyflow/svelte';
  import LynxKiteNode from './LynxKiteNode.svelte';
  import NodeParameter from './NodeParameter.svelte';
  type $$Props = NodeProps;
  export let id: $$Props['id'];
  export let data: $$Props['data'];
  const { updateNodeData } = useSvelteFlow();
  const updateNodeInternals = useUpdateNodeInternals();
  $: metaParams = data.meta?.params;
  $: store = getContext('LynxKite store');
  function setParam(name, newValue) {
    const i = $store.workspace.nodes.findIndex((n) => n.id === id);
    $store.workspace.nodes[i].data.params[name] = newValue;
    updateNodeInternals();
  }
</script>

<LynxKiteNode {...$$props}>
  {#each Object.entries(data.params) as [name, value]}
    <NodeParameter
      {name}
      {value}
      meta={metaParams?.[name]}
      onChange={(value) => setParam(name, value)}
      />
  {/each}
  <slot />
</LynxKiteNode>
